### ISSUE TITLE
bug?refresh_token grant

### ISSUE THREAD

**Issue by nicolaslei** [preferans/oauth-bridge#2]
*POST /access_token*
`grant_type=refresh_token&client_id=xxxx&refresh_token=O6-z-mIIcNdCUOuenN2--....`
>No `scope` parameters

error
>PHP Warning:  trim() expects parameter 1 to be string, array given in xx\vendor\preferans\oauth-bridge\src\Server\Grant\AbstractGrant.php on line 189

```php
$scopes = $this->getScopesFromRequest($request, false, null, $oldRefreshToken['scopes']);
```
>$oldRefreshToken['scopes'] is array

**Comment by nicolaslei** [comment]
Preferans\Oauth\Server\Grant\RefreshTokenGrant errors
on line 59
```php
if (!in_array($scope->getIdentifier(), explode(' ', $oldRefreshToken['scopes']))) {
    throw OAuthServerException::invalidScope($scope->getIdentifier());
}
```
on line 79
```php
if (in_array($scope->getIdentifier(), explode(' ', $oldRefreshToken['scopes'])) === false) {
    throw OAuthServerException::invalidScope($scope->getIdentifier());
}
```

**Comment by sergeyklay** [comment]
@nicolaslei Fixed in latest stable release. Thank you for the report.
